sequenceDiagram
    participant browser
    participant server

    browser->>server: POST - https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    server-->>browser: HTML Document
    deactivate server

    browser->>server: GET - https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: HTML Document
    deactivate server

    browser->>server: GET - https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: CSS Document
    deactivate server

    browser->>server: GET - https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: JavaScript Document
    deactivate server

    browser->>server: GET - https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: {content: "hey", date: "2024-01-02T15:42:19.246Z"}
    deactivate server
    
    Note right of browser:  The browser executes the callabck function that renders the note.