sequenceDiagram
    Browser ->> Server: POST - https://studies.cs.helsinki.fi/exampleapp/new_note
    Server -->> Browser: HTML Document
    Browser ->> Server: GET - https://studies.cs.helsinki.fi/exampleapp/notes
    Server -->> Browser: HTML Document
    Browser ->> Server: GET - https://studies.cs.helsinki.fi/exampleapp/main.css
    Server -->> Browser: CSS Document
    Browser ->> Server: GET - https://studies.cs.helsinki.fi/exampleapp/main.js
    Server -->> Browser: JavaScript Document
    Browser ->> Server: GET - https://studies.cs.helsinki.fi/exampleapp/data.json
    Server -->> Browser: {content: "hey", date: "2024-01-02T15:42:19.246Z"}
    Note right of Browser:  The browser executes the callabck function that renders the note.