sequenceDiagram
    participant browser
    participant server

    browser->>server: POST - https://studies.cs.helsinki.fi/exampleapp/new_note
    server-->>browser: HTML Document

    browser->>server: GET - https://studies.cs.helsinki.fi/exampleapp/notes
    server-->>browser: HTML Document

    browser->>server: GET - https://studies.cs.helsinki.fi/exampleapp/main.css
    server-->>browser: CSS Document

    browser->>server: GET - https://studies.cs.helsinki.fi/exampleapp/main.js
    server-->>browser: JavaScript Document

    browser->>server: GET - https://studies.cs.helsinki.fi/exampleapp/data.json
    server-->>browser: {content: "hey", date: "2024-01-02T15:42:19.246Z"}
    
    Note right of browser:  The browser executes the callabck function that renders the note.